version: 2

# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: check TERM
          command: |
            echo ${TERM}
      - run:
          name: check echo color
          command: |
            echo -e "\e[31mhoge\e[m"
      - run:
          name: check ruby color
          command: |
            docker run -it --rm -v ${PWD}:/work -w /work ruby:alpine ruby ./color.rb

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build

